import { PaletteColors } from '../definitions';

export const DEFAULT_PALETTE = {
  background: "#252525",
  foreground: "#ffffff",
  backgroundLight: "#444444",
  accentPrimary: "#0284f7",
  accentSecondary: "#0284f7",
  text: "#ffffff"
};

export const DEFAULT_THEME_TEMPLATE_DARK = {
  palette: {
    background: 0,
    backgroundLight: 17,
    text: 15,
    accentPrimary: 1,
    accentSecondary: 2,
    textFocus: 16,
  },
  browser: {
    icons: PaletteColors.AccentPrimary,
    icons_attention: PaletteColors.AccentSecondary,
    frame: PaletteColors.Background,
    tab_text: PaletteColors.TextFocus,
    tab_loading: PaletteColors.AccentPrimary,
    tab_background_text: PaletteColors.Text,
    tab_selected: PaletteColors.BackgroundLight,
    tab_line: PaletteColors.AccentPrimary,
    tab_background_separator: PaletteColors.Background,
    toolbar: PaletteColors.BackgroundLight,
    toolbar_field: PaletteColors.BackgroundLight,
    toolbar_field_focus: PaletteColors.BackgroundLight,
    toolbar_field_text: PaletteColors.Text,
    toolbar_field_text_focus: PaletteColors.TextFocus,
    toolbar_field_border: PaletteColors.Background,
    toolbar_field_border_focus: PaletteColors.BackgroundLight,
    toolbar_field_separator: PaletteColors.Background,
    toolbar_field_highlight: PaletteColors.AccentPrimary,
    toolbar_field_highlight_text: PaletteColors.Background,
    toolbar_bottom_separator: PaletteColors.Background,
    toolbar_top_separator: PaletteColors.Background,
    toolbar_vertical_separator: PaletteColors.BackgroundLight,
    ntp_background: PaletteColors.Background,
    ntp_text: PaletteColors.Text,
    popup: PaletteColors.BackgroundLight,
    popup_border: PaletteColors.BackgroundLight,
    popup_text: PaletteColors.Text,
    popup_highlight: PaletteColors.AccentPrimary,
    popup_highlight_text: PaletteColors.Background,
    sidebar: PaletteColors.Background,
    sidebar_border: PaletteColors.BackgroundLight,
    sidebar_text: PaletteColors.Text,
    sidebar_highlight: PaletteColors.AccentPrimary,
    sidebar_highlight_text: PaletteColors.TextFocus,
    bookmark_text: PaletteColors.TextFocus,
    button_background_hover: PaletteColors.Background,
    button_background_active: PaletteColors.Background,
  }
};

export const DEFAULT_THEME_TEMPLATE_LIGHT = {
  palette: {
    background: 15,
    backgroundLight: 16,
    text: 17,
    accentPrimary: 1,
    accentSecondary: 2,
    textFocus: 0,
  },
  browser: {
    icons: PaletteColors.AccentPrimary,
    icons_attention: PaletteColors.AccentSecondary,
    frame: PaletteColors.Background,
    tab_text: PaletteColors.TextFocus,
    tab_loading: PaletteColors.AccentPrimary,
    tab_background_text: PaletteColors.Text,
    tab_selected: PaletteColors.BackgroundLight,
    tab_line: PaletteColors.AccentPrimary,
    tab_background_separator: PaletteColors.Background,
    toolbar: PaletteColors.BackgroundLight,
    toolbar_field: PaletteColors.BackgroundLight,
    toolbar_field_focus: PaletteColors.BackgroundLight,
    toolbar_field_text: PaletteColors.Text,
    toolbar_field_text_focus: PaletteColors.TextFocus,
    toolbar_field_border: PaletteColors.Background,
    toolbar_field_border_focus: PaletteColors.BackgroundLight,
    toolbar_field_separator: PaletteColors.Background,
    toolbar_field_highlight: PaletteColors.AccentPrimary,
    toolbar_field_highlight_text: PaletteColors.Background,
    toolbar_bottom_separator: PaletteColors.Background,
    toolbar_top_separator: PaletteColors.Background,
    toolbar_vertical_separator: PaletteColors.BackgroundLight,
    ntp_background: PaletteColors.Background,
    ntp_text: PaletteColors.Text,
    popup: PaletteColors.BackgroundLight,
    popup_border: PaletteColors.BackgroundLight,
    popup_text: PaletteColors.Text,
    popup_highlight: PaletteColors.AccentPrimary,
    popup_highlight_text: PaletteColors.Background,
    sidebar: PaletteColors.Background,
    sidebar_border: PaletteColors.BackgroundLight,
    sidebar_text: PaletteColors.Text,
    sidebar_highlight: PaletteColors.AccentPrimary,
    sidebar_highlight_text: PaletteColors.TextFocus,
    bookmark_text: PaletteColors.TextFocus,
    button_background_hover: PaletteColors.Background,
    button_background_active: PaletteColors.Background,
  }
}
