export const PALETTE_TEMPLATE_DATA = [
  { title: 'Background', description: 'Main background color', target: 'background' },
  { title: 'Background light', description: 'Secondary background color', target: 'backgroundLight' },
  { title: 'Text', description: 'Main text color', target: 'text' },
  { title: 'Text focus', description: 'Text used in the current tab, etc.', target: 'textFocus' },
  { title: 'Accent primary', description: 'Main accent color, used for icons', target: 'accentPrimary' },
  { title: 'Accent secondary', description: 'Mainly used for hovers and highlights', target: 'accentSecondary' },
];

export const THEME_TEMPLATE_DATA = [
  { title: 'Icons', description: 'The color of toolbar icons, excluding those in the find toolbar.' },
  { title: 'Icons attention', description: 'The color of toolbar icons in attention state, e.g. the starred bookmark icon.' },
  { title: 'Frame', description: 'The color of the header area background.' },
  { title: 'Tab text', description: 'The text color for the selected tab.' },
  { title: 'Tab loading', description: 'The color of the tab loading indicator and the tab loading burst.' },
  { title: 'Tab background text', description: 'The color of the text displayed in the inactive page tabs.' },
  { title: 'Tab selected', description: 'The background color of the selected tab.' },
  { title: 'Tab line', description: 'The color of the selected tab line.' },
  { title: 'Tab background separator', description: 'The color of the vertical separator of the background tabs.' },
  { title: 'Toolbar', description: 'The background color for the navigation bar, the bookmarks bar, and the selected tab.' },
  { title: 'Toolbar field', description: 'The background color for fields in the toolbar, such as the URL bar.' },
  { title: 'Toolbar field focus', description: 'The focused background color for fields in the toolbar, such as the URL bar.' },
  { title: 'Toolbar field text', description: 'The color of text in fields in the toolbar, such as the URL bar.' },
  { title: 'Toolbar field text focus', description: 'The color of text in focused fields in the toolbar, such as the URL bar.' },
  { title: 'Toolbar field border', description: 'The border color for fields in the toolbar.' },
  { title: 'Toolbar field border focus', description: 'The focused border color for fields in the toolbar.' },
  { title: 'Toolbar field separator', description: 'The color of separators inside the URL bar.' },
  { title: 'Toolbar field highlight', description: 'The background color used to indicate the current selection of text in the URL bar.' },
  { title: 'Toolbar field highlight text', description: 'The color used to draw text that\'s currently selected in the URL bar.' },
  { title: 'Toolbar bottom_separator', description: 'The color of the line separating the bottom of the toolbar from the region below.' },
  { title: 'Toolbar top separator', description: 'The color of the line separating the top of the toolbar from the region above.' },
  { title: 'Toolbar vertical separator', description: 'The color of the separator next to the application menu icon.' },
  { title: 'New tab page background', description: 'The new tab page background color.' },
  { title: 'New tab page text', description: 'The new tab page text color.' },
  { title: 'Popup', description: 'The background color of popups (eg. url bar dropdown and arrow panels).' },
  { title: 'Popup border', description: 'The border color of popups.' },
  { title: 'Popup text', description: 'The text color of popups.' },
  { title: 'Popup highlight', description: 'The background color of items highlighted using the keyboard inside popups.' },
  { title: 'Popup highlight text', description: 'The text color of items highlighted inside popups.' },
  { title: 'Sidebar', description: 'The background color of the sidebar.' },
  { title: 'Sidebar border', description: 'The border and splitter color of the browser sidebar' },
  { title: 'Sidebar text', description: 'The text color of sidebars.' },
  { title: 'Sidebar highlight', description: 'The background color of highlighted rows in built-in sidebars' },
  { title: 'Sidebar highlight text', description: 'The text color of highlighted rows in sidebars.' },
  { title: 'Bookmark text', description: 'The color of text and icons in the bookmark and find bars.' },
  { title: 'Button background hover', description: 'The color of the background of the toolbar buttons on hover.' },
  { title: 'Button background active', description: 'The color of the background of the pressed toolbar buttons.' },
];
